name: Dependency Scan
on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'  # Run weekly

jobs:
  dependency-check:
    name: OWASP Dependency Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      pull-requests: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Create reports directory
        run: mkdir -p reports
      
      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}
        with:
          project: 'Vulnerable Node.js App'
          path: '.'
          format: 'SARIF'
          out: 'reports'
          args: >
            --enableExperimental
            --scan .
            --suppression ./suppression.xml
            --failOnCVSS 7

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: reports/dependency-check-report.sarif
            
      - name: Generate HTML Report
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}
        with:
          project: 'Vulnerable Node.js App'
          path: '.'
          format: 'HTML'
          out: 'reports'
          args: >
            --enableExperimental
            --scan .
            --suppression ./suppression.xml
            --failOnCVSS 7
            
      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Dependency Check Report
          path: reports
          retention-days: 5
      
      - name: Create PR Comment
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: dependency-check-results
          message: |
            ### OWASP Dependency Check Results
            
            For detailed results, check the Security tab and download the HTML report from Artifacts.
            To view the report:
            1. Go to the Actions tab
            2. Click on this workflow run
            3. Download the "Dependency Check Report" artifact 