name: Secret Scanning
on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main

jobs:
  trufflehog:
    name: TruffleHog Secret Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.pull_request.base.sha || github.event.before }}
          head: ${{ github.event.pull_request.head.sha || github.event.after }}
          extra_args: --debug --only-verified --json
          output: trufflehog-results.json

      - name: Convert JSON to SARIF
        if: always()
        run: |
          echo '{
            "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
            "version": "2.1.0",
            "runs": [
              {
                "tool": {
                  "driver": {
                    "name": "TruffleHog",
                    "rules": []
                  }
                },
                "results": ['$(cat trufflehog-results.json | jq -r 'map({
                  "ruleId": "secret-detection",
                  "level": "error",
                  "message": { "text": .Description },
                  "locations": [{
                    "physicalLocation": {
                      "artifactLocation": { "uri": .SourceMetadata.Data.Git.file },
                      "region": { "startLine": .SourceMetadata.Data.Git.line }
                    }
                  }]
                }) | join(",")')']
              }
            ]
          }' > trufflehog-results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: trufflehog-results.sarif
          category: trufflehog
      
      - name: Add PR Comment
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: trufflehog-results
          message: |
            ### TruffleHog Secret Scanning Results
            
            For detailed results, check the Security tab and Actions logs.
            ⚠️ Make sure to remove any detected secrets and rotate them if they were valid. 